#%%
JOB_CAT = 'Job Category'

JOB_TITLE = 'Job Title'
SALARY_ESTIMATE = 'Salary Estimate'
JOB_DES = 'Job Description'
RATING = 'Rating'
CO_NAME = 'Company Name'
LOCATION = 'Location'
HEADQUARTERS = 'Headquarters'
SIZE = 'Size'
FOUNDED = 'Founded'
OWNERSHIP_TYPE = 'Type of ownership'
INDUSTRY = 'Industry'
SECTOR = 'Sector'
REVENUE = 'Revenue'
COMPETITORS = 'Competitors'
EASY_APPLY = 'Easy Apply'

SALARY_LOWER = 'Salary Lower'
SALARY_UPPER = 'Salary Upper'